### ISSUE TITLE
How to package extension?

### ISSUE THREAD

**Issue by kengelke** [dgil/generator-firefox-extension#1]
The scaffold created by the app works great. But how do I create a package for my extension that I can publish on AMO?

**Comment by dgil** [comment]
Hi @kengelke! You only need to run `cfx xpi --pkgdir=app` and you'll get the `.xpi` that you can upload to AMO. More info on Firefox's developer wiki: [submitting an add-on to AMO](https://developer.mozilla.org/en-US/Add-ons/Submitting_an_add-on_to_AMO).

FYI: I'm planning to add in the next version a `grunt build` command (which will run the tests and create the `xpi` package with all files minified) to make the process of build easier.

**Comment by turbohz** [comment]
@dgil , this thread needs moar gifs
![post-46491-laughing-lizard-gif-imgur-gfyc-mmvg](https://cloud.githubusercontent.com/assets/61641/6776632/65e62da6-d141-11e4-975e-8b7a321d003a.gif)

**Comment by kengelke** [comment]
Thanks for the quick help!
