### ISSUE TITLE
The system can not find the path specified

### ISSUE THREAD

**Issue by JesuanT** [dgil/generator-firefox-extension#2]
When I run:
    grunt watch
and modify the files, console warns me as above for Windows Ultimate 64.

I tried to change --post-file location with backslashes for Windows compatibility but did not help.

Also getting" failed: unknown error" while connecting to localhost.

Any ideas please?

**Comment by dgil** [comment]
@JesuanT Sadly I don't have a PC with Windows. I've found this [issue](https://github.com/palant/autoinstaller/issues/2 issue) with _Extension Auto-Installer_ and Windows. Can you check [this answer](https://github.com/palant/autoinstaller/issues/2#issuecomment-66927288) and tell me if it works?

**Comment by JesuanT** [comment]
@dgil Thank you very much for your help. I thought running "grunt watch" would automatically start Firefox. I opened Firefox first and then run the "grunt watch". This fixed the issue.

But when I modify package.json for the add-on, say if the name and description of the add-on is changed, the changes are not grabbed. Any thoughts on this please?

Thanks again.

**Comment by dgil** [comment]
@JesuanT many thanks for reporting these bugs.

I've just released a new version (`v0.3.1`) with a fix for `grunt watch` task to watch all files (instead of only `js` and `html`). Also I've updated the `readme` file with Firefox running requirement in `grunt watch`.

**Comment by JesuanT** [comment]
@dgil I thank you for your prompt help and fix for the issue. Keep up the great work.
